php_53:
  restart: always
  build: php
  volumes:
    - /var/local/secret/eea.docker.uwwtd_web_dem:/var/www/UWWTD-WEB-DEM/application/configs
  volumes_from:
    - uwwtd_web_dem_home_5_3
  ports:
    - "50004:80"
  links:
    - php_53_database:database

php_53_database:
  restart: always
  image: mysql:5.5
  volumes_from:
    - uwwtd_web_dem_data_5_3
