home:
  restart: always
  build: php
  volumes:
    - /var/local/secret/eea.docker.uwwtd_web_dem:/var/www/UWWTD-WEB-DEM/application/configs:ro
  volumes_from:
    - uwwtd_web_dem_home
  ports:
    - "50004:80"
  links:
    - database:database

database:
  restart: always
  image: mysql:5.5
  volumes_from:
    - uwwtd_web_dem_data
